language: java

sudo: false

jdk:
  - openjdk11

branches:
  only:
    master

before_script:
  - cp test/resources/ndex-server.properties.sample test/resources/ndex-server.properties
  - sed -i 's/PLACEHOLDER_HOST/'"$SERVER_HOST"'/g' test/resources/ndex-server.properties
  - sed -i 's/PLACEHOLDER_USERNAME/'"$SERVER_USERNAME"'/g' test/resources/ndex-server.properties
  - sed -i 's/PLACEHOLDER_PASSWORD/'"$SERVER_PASSWORD"'/g' test/resources/ndex-server.properties
  
# deploy:
#   provider: script
#   script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
#   skip_cleanup: true
