language: java

sudo: false

jdk:
  - openjdk11

branches:
  only:
    master
    
# deploy:
#   provider: script
#   script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
#   skip_cleanup: true
